name: fiberhome_hg5382a PonWrt
on:
  workflow_dispatch: # 手动触发，网页点Run workflow

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装编译依赖
        run: |
          sudo apt update
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
            bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
            g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
            libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
            libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
            ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
            python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
            upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd

      - name: 克隆 PonWrt 源码
        run: |
          git clone https://github.com/pbs05/ponwrt.git
          cd PonWrt

      - name: Feeds更新 & 导入配置
        run: |
          cd PonWrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cp configs/an7581.config .config
          make defconfig

      - name: 预下载源码包
        run: |
          cd PonWrt
          make download -j$(nproc)

      - name: 编译固件
        run: |
          cd PonWrt
          make -j$(nproc) V=s

      - name: 上传固件Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PonWrt-Firmware
          path: PonWrt/bin/targets/**/*.bin
